# sops-nix configuration
# Defines which keys can encrypt/decrypt which files

keys:
  # Diego's age key (from ~/.config/sops/age/keys.txt)
  - &diego age1u575hx8h4t5cgle2uznmyfy75e7cgd02h9t5dax506luz9e05vlqxtd7pq

creation_rules:
  # All yaml files in secrets/ directory
  - path_regex: secrets/.*\.yaml$
    key_groups:
      - age:
          - *diego

  # All json files in secrets/ directory
  - path_regex: secrets/.*\.json$
    key_groups:
      - age:
          - *diego
