# ╔═══════════════════════════════════════════════════════════════════════════╗
# ║                           NIXOS BIFROST                                    ║
# ║                                                                            ║
# ║   NixOS companion to Kinoite Bifrost                                      ║
# ║                                                                            ║
# ║   Sessions: KDE Plasma, Openbox, Waydroid, Kiosk modes, ChromiumOS-style  ║
# ║                                                                            ║
# ╚═══════════════════════════════════════════════════════════════════════════╝

{ config, pkgs, lib, ... }:

{
  # System basics
  system.stateVersion = "24.11";

  # Boot configuration
  boot = {
    loader = {
      systemd-boot.enable = true;
      efi.canTouchEfiVariables = true;
    };
    # Use latest kernel for Surface Pro hardware support
    kernelPackages = pkgs.linuxPackages_latest;

    # Enable kernel modules for Waydroid
    kernelModules = [ "ashmem_linux" "binder_linux" ];
    extraModulePackages = with config.boot.kernelPackages; [
      # Waydroid kernel modules (if available)
    ];
  };

  # Filesystem - use mkDefault to allow nixos-generators to override
  # For actual installation, this will be generated by nixos-generate-config
  fileSystems."/" = lib.mkDefault {
    device = "/dev/disk/by-label/nixos";
    fsType = "ext4";
  };

  # Networking
  networking = {
    hostName = "surface-nixos";
    networkmanager.enable = true;
    firewall = {
      enable = true;
      allowedTCPPorts = [ 22 ];
    };
  };

  # Timezone and locale
  time.timeZone = "Europe/Madrid";
  i18n.defaultLocale = "en_US.UTF-8";

  # ═══════════════════════════════════════════════════════════════════════════
  # USER ACCOUNT
  # ═══════════════════════════════════════════════════════════════════════════

  users.users.user = {
    isNormalUser = true;
    description = "Default User";
    initialPassword = "1234567890";
    extraGroups = [ "wheel" "networkmanager" "video" "audio" "docker" "kvm" "libvirtd" ];
    shell = pkgs.fish;
  };

  # Passwordless sudo for wheel
  security.sudo.wheelNeedsPassword = false;

  # ═══════════════════════════════════════════════════════════════════════════
  # SESSION 1: KDE PLASMA 6 (Default)
  # ═══════════════════════════════════════════════════════════════════════════

  services.desktopManager.plasma6.enable = true;
  services.displayManager.sddm = {
    enable = true;
    wayland.enable = true;
  };

  # ═══════════════════════════════════════════════════════════════════════════
  # SESSION 2: OPENBOX (X11 Lightweight)
  # ═══════════════════════════════════════════════════════════════════════════

  services.xserver = {
    enable = true;
    xkb.layout = "us";

    # Openbox window manager
    windowManager.openbox.enable = true;
  };

  # ═══════════════════════════════════════════════════════════════════════════
  # SESSION 3: WAYDROID (Android Container)
  # ═══════════════════════════════════════════════════════════════════════════

  virtualisation.waydroid.enable = true;

  # ═══════════════════════════════════════════════════════════════════════════
  # SESSION 4: CAGE (Wayland Kiosk Compositor)
  # ═══════════════════════════════════════════════════════════════════════════

  # Cage is a Wayland kiosk compositor - wraps a single app fullscreen
  # Used for: Tor Kiosk, Chrome Kiosk, ChromiumOS-style session

  # ═══════════════════════════════════════════════════════════════════════════
  # SESSION 5: CHROMIUMOS-STYLE (Lightweight Chrome-centric)
  # ═══════════════════════════════════════════════════════════════════════════

  # ChromiumOS-style experience using Wayland + Chromium
  # Alternative: Use FydeOS or chromeOS Flex in VM

  # ═══════════════════════════════════════════════════════════════════════════
  # SSH
  # ═══════════════════════════════════════════════════════════════════════════

  services.openssh = {
    enable = true;
    settings = {
      PasswordAuthentication = true;
      PermitRootLogin = "no";
    };
  };

  # ═══════════════════════════════════════════════════════════════════════════
  # AUDIO (Pipewire)
  # ═══════════════════════════════════════════════════════════════════════════

  security.rtkit.enable = true;
  services.pipewire = {
    enable = true;
    alsa.enable = true;
    alsa.support32Bit = true;
    pulse.enable = true;
  };

  # ═══════════════════════════════════════════════════════════════════════════
  # HARDWARE
  # ═══════════════════════════════════════════════════════════════════════════

  # Bluetooth
  hardware.bluetooth = {
    enable = true;
    powerOnBoot = true;
  };

  # Graphics (Intel/AMD/NVIDIA)
  hardware.graphics = {
    enable = true;
    enable32Bit = true;
  };

  # ═══════════════════════════════════════════════════════════════════════════
  # CONTAINERS (Docker + Podman)
  # ═══════════════════════════════════════════════════════════════════════════

  virtualisation = {
    docker.enable = true;
    podman = {
      enable = true;
      dockerCompat = false;
    };
    libvirtd.enable = true;
  };

  # ═══════════════════════════════════════════════════════════════════════════
  # NIX SETTINGS
  # ═══════════════════════════════════════════════════════════════════════════

  nix = {
    settings = {
      experimental-features = [ "nix-command" "flakes" ];
      auto-optimise-store = true;
    };
    gc = {
      automatic = true;
      dates = "weekly";
      options = "--delete-older-than 7d";
    };
  };

  # ═══════════════════════════════════════════════════════════════════════════
  # SYSTEM PACKAGES
  # ═══════════════════════════════════════════════════════════════════════════

  environment.systemPackages = with pkgs; [
    # ─── Core CLI tools ───────────────────────────────────────────────────────
    vim neovim git curl wget htop btop tree jq yq fd ripgrep fzf
    tmux screen zoxide starship eza bat

    # ─── System tools ─────────────────────────────────────────────────────────
    pciutils usbutils lsof file unzip p7zip pv

    # ─── Network tools ────────────────────────────────────────────────────────
    nmap dig tcpdump

    # ─── Development ──────────────────────────────────────────────────────────
    gcc gnumake cmake
    python3 python312Packages.pip
    nodejs_22 nodePackages.npm
    rustc cargo

    # ─── Cloud CLI ────────────────────────────────────────────────────────────
    google-cloud-sdk

    # ─── Container tools ──────────────────────────────────────────────────────
    docker-compose podman-compose buildah skopeo

    # ─── Desktop apps ─────────────────────────────────────────────────────────
    firefox
    chromium
    tor-browser
    kate
    konsole
    dolphin

    # ─── Openbox session components ───────────────────────────────────────────
    openbox
    obconf
    polybar
    nitrogen
    feh
    rofi
    dunst
    picom
    xterm

    # ─── Wayland kiosk ────────────────────────────────────────────────────────
    cage
    wlr-randr

    # ─── Session utilities ────────────────────────────────────────────────────
    zenity
    kdialog

    # ─── VM tools ─────────────────────────────────────────────────────────────
    virt-manager
    virt-viewer
    qemu
    OVMF
  ];

  # ═══════════════════════════════════════════════════════════════════════════
  # SHELLS
  # ═══════════════════════════════════════════════════════════════════════════

  programs.fish.enable = true;
  programs.bash.completion.enable = true;

  # ═══════════════════════════════════════════════════════════════════════════
  # GIT
  # ═══════════════════════════════════════════════════════════════════════════

  programs.git = {
    enable = true;
    config = {
      init.defaultBranch = "main";
    };
  };

  # ═══════════════════════════════════════════════════════════════════════════
  # FONTS
  # ═══════════════════════════════════════════════════════════════════════════

  fonts.packages = with pkgs; [
    noto-fonts
    noto-fonts-cjk-sans
    noto-fonts-emoji
    liberation_ttf
    fira-code
    fira-code-symbols
    jetbrains-mono
    (nerdfonts.override { fonts = [ "FiraCode" "JetBrainsMono" ]; })
  ];

  # ═══════════════════════════════════════════════════════════════════════════
  # FLATPAK (for apps not in nixpkgs)
  # ═══════════════════════════════════════════════════════════════════════════

  services.flatpak.enable = true;

  # ═══════════════════════════════════════════════════════════════════════════
  # CUSTOM SESSION FILES
  # ═══════════════════════════════════════════════════════════════════════════

  # Create custom Wayland session files
  environment.etc = {
    # Android (Waydroid) session
    "wayland-sessions/android.desktop".text = ''
      [Desktop Entry]
      Name=Android (Waydroid)
      Comment=Full Android UI via Waydroid
      Exec=cage -- waydroid show-full-ui
      Type=Application
      DesktopNames=Android
    '';

    # Tor Kiosk session
    "wayland-sessions/tor-kiosk.desktop".text = ''
      [Desktop Entry]
      Name=Tor Kiosk
      Comment=Anonymous browsing with Tor Browser
      Exec=cage -- tor-browser
      Type=Application
      DesktopNames=TorKiosk
    '';

    # Chrome Kiosk session
    "wayland-sessions/chrome-kiosk.desktop".text = ''
      [Desktop Entry]
      Name=Chrome Kiosk
      Comment=Chromium in kiosk mode
      Exec=cage -- chromium --kiosk --start-fullscreen
      Type=Application
      DesktopNames=ChromeKiosk
    '';

    # ChromiumOS-style session (minimal desktop, Chrome-centric)
    "wayland-sessions/chromiumos.desktop".text = ''
      [Desktop Entry]
      Name=ChromiumOS Style
      Comment=Minimal Chrome-centric desktop
      Exec=cage -- chromium --start-maximized --enable-features=WebUIDarkMode
      Type=Application
      DesktopNames=ChromiumOS
    '';
  };
}
